#import "@preview/ieee-monolith:0.1.0": ieee

#show: ieee.with(
  title: [Exploring U.S. Traffic Accident Data, 2016–2020 or (Exploratory Analysis and Data-Driven Insights into U.S. Traffic Accidents)],
  authors: (
    (
      name: "Adityo Leonard",
      department: [Department of Civil and Environmental Engineering],
      organization: [University of Illinois Urbana-Champaign],
      location: [Urbana, IL, USA],
      email: "adityol2@illinois.edu",
    ),
    (
      name: "Akram Muhammad",
      department: [Department of Civil and Environmental Engineering],
      organization: [University of Illinois Urbana-Champaign],
      location: [Urbana, IL, USA],
      email: "akramm3@illinois.edu",
    ),
    (
      name: "Dumehlezi Jordan Mthombeni",
      department: [Department of Civil and Environmental Engineering],
      organization: [University of Illinois Urbana-Champaign],
      location: [Urbana, IL, USA],
      email: "dmtho@illinois.edu",
    ),
    (
      name: "Mohammadreza Rajaee",
      department: [Department of Civil and Environmental Engineering],
      organization: [University of Illinois Urbana-Champaign],
      location: [Urbana, IL, USA],
      email: "mrajaee2@illinois.edu",
    )
  ),
  index-terms: ("Optional", "Keywords", "Here"),
  bibliography: bibliography("refs.bib"),
)

= Data Description

The dataset used in this project is the US Traffic Accidents dataset, available on Kaggle, which covers traffic crashes in the United States from 2016 to 2020. The dataset can be accessed at https://www.kaggle.com/datasets/jonbown/us-2020-traffic-accidents/data. This dataset was generated by sampling records from the National Highway Traffic Safety Administration’s (NHTSA) Crash Report Sampling System (CRSS). CRSS itself is designed to provide a nationally representative sample of police-reported motor vehicle crashes in the United States. To develop CRSS, NHTSA uses a probability-based sampling process to select crash reports from law-enforcement agencies in selected geographic areas across the country. The selected police crash reports are then reviewed, interpreted, and coded by trained CRSS coders into standardized electronic data files.

The US Traffic Accidents dataset covers 259,077 crashes from 2016 through 2020 and is provided in CSV format. The records are organized into three main types of files: accident (acc), containing crash-level information; vehicle (veh), containing information about vehicles involved in each crash; and person (pers), containing information about drivers, passengers, pedestrians, and other persons involved. These files can be linked using the common CASENUM variable. Broadly, the dataset contains attributes describing the location and roadway characteristics of the crash, date and time, weather and environmental conditions, crash characteristics and contributing factors, vehicle information, and demographic or injury information for people involved in the crash.

Table 1 summarizes the main attributes that are expected to be relevant to this project; the complete CRSS dataset contains additional variables related to crash, vehicle, and person characteristics.


#show figure: set block(breakable: true)
#figure(
  caption: [Attributes of the U.S. Traffic Accidents Dataset],
  table(
    columns: (5%, 20%, 55%, 20%),
    align: (center, center, left, center),
    inset: 4pt,

    table.header(
      [*No.*],
      [*Attribute*],
      [*Description*],
      [*Type / Unit*],
    ),

    [`1`],
    [`CASENUM`],
    [Unique case number assigned to each sampled crash. Used to identify a crash and link it with vehicle and person records.],
    [Identifier],

    [`2`],
    [`PSU`],
    [Primary Sampling Unit representing the geographic area from which the police crash report was sampled. A PSU generally consists of a county or group of counties.],
    [Categorical code],

    [`3`],
    [`PJ`],
    [Police Jurisdiction from which the police crash report was sampled.],
    [Categorical code],

    [`4`],
    [`STRATUM`],
    [Sampling stratum into which the police crash report was classified during CRSS sampling.],
    [Categorical code],

    [`5`],
    [`VE_TOTAL`],
    [Number of vehicle forms submitted for the crash; represents the total vehicles recorded in the case.],
    [Count],

    [`6`],
    [`VE_FORMS`],
    [Number of motor vehicles in transport involved in the crash.],
    [Count],

    [`7`],
    [`PVH_INVL`],
    [Number of parked or working vehicles involved in the crash.],
    [Count],

    [`8`],
    [`PEDS`],
    [Number of forms submitted for persons who were not occupants of motor vehicles, such as pedestrians or cyclists.],
    [Count],

    [`9`],
    [`PERMVIT`],
    [Number of persons occupying motor vehicles in transport.],
    [Count],

    [`10`],
    [`PERNOTMVIT`],
    [Number of persons involved in the crash who were not in motor vehicles in transport.],
    [Count],

    [`11`],
    [`NUM_INJ`],
    [Number of people injured in the crash.],
    [Persons],

    [`12`],
    [`MONTH`],
    [Month in which the crash occurred.],
    [1–12],

    [`13`],
    [`YEAR`],
    [Calendar year in which the crash occurred.],
    [Year],

    [`14`],
    [`DAY_WEEK`],
    [Day of the week on which the crash occurred.],
    [Categorical code],

    [`15`],
    [`HOUR`],
    [Hour at which the crash occurred.],
    [Hour, 0–23],

    [`16`],
    [`MINUTE`],
    [Minute at which the crash occurred.],
    [Minute, 0–59],

    [`17`],
    [`HARM_EV`],
    [First harmful event associated with the crash, such as collision with another vehicle, pedestrian, or fixed object.],
    [Categorical code],

    [`18`],
    [`ALCOHOL`],
    [Indicates whether alcohol involvement was identified in the crash.],
    [Categorical code],

    [`19`],
    [`MAX_SEV`],
    [Maximum injury severity among all persons involved in the crash.],
    [Categorical / ordinal],

    [`20`],
    [`MAN_COLL`],
    [Manner of collision associated with the first harmful event, such as rear-end, head-on, or angle collision.],
    [Categorical code],

    [`21`],
    [`RELJCT1`],
    [Indicates whether the crash occurred within an interchange area.],
    [Categorical code],

    [`22`],
    [`RELJCT2`],
    [Describes the specific relationship of the crash location to a junction, such as an intersection or driveway.],
    [Categorical code],

    [`23`],
    [`TYP_INT`],
    [Type of intersection associated with the crash.],
    [Categorical code],

    [`24`],
    [`WRK_ZONE`],
    [Indicates whether the crash occurred in or was related to a work zone.],
    [Categorical code],

    [`25`],
    [`REL_ROAD`],
    [Describes the location of the crash relative to the trafficway, such as on the roadway, shoulder, median, or roadside.],
    [Categorical code],

    [`26`],
    [`LGT_COND`],
    [Lighting condition at the time of the crash, such as daylight, darkness, dawn, or dusk.],
    [Categorical code],

    [`27`],
    [`WEATHER1`],
    [First atmospheric/weather condition recorded for the crash.],
    [Categorical code],

    [`28`],
    [`WEATHER2`],
    [Second atmospheric/weather condition recorded when more than one condition applied.],
    [Categorical code],

    [`29`],
    [`WEATHER`],
    [Derived atmospheric condition used to summarize the prevailing weather at the time of the crash.],
    [Categorical code],

    [`30`],
    [`SCH_BUS`],
    [Indicates whether the crash was related to a school bus.],
    [Categorical code],

    [`31`],
    [`INT_HWY`],
    [Indicates whether the crash occurred on an Interstate Highway.],
    [Categorical code],

    [`32`],
    [`CF1`],
    [First crash-level related factor reported in the crash record.],
    [Categorical code],

    [`33`],
    [`CF2`],
    [Second crash-level related factor reported in the crash record.],
    [Categorical code],

    [`34`],
    [`CF3`],
    [Third crash-level related factor reported in the crash record.],
    [Categorical code],

    [`35`],
    [`WKDY_IM`],
    [Imputed version of `DAY_WEEK`, used when the original day-of-week information is missing or unknown.],
    [Categorical code],

    [`36`],
    [`HOUR_IM`],
    [Imputed version of the crash hour.],
    [Hour / categorical code],

    [`37`],
    [`MINUTE_IM`],
    [Imputed version of the crash minute.],
    [Minute / categorical code],

    [`38`],
    [`EVENT1_IM`],
    [Imputed version of the first harmful event (`HARM_EV`).],
    [Categorical code],

    [`39`],
    [`MANCOL_IM`],
    [Imputed version of the manner of collision (`MAN_COLL`).],
    [Categorical code],

    [`40`],
    [`RELJCT1_IM`],
    [Imputed version of the interchange-area relationship (`RELJCT1`).],
    [Categorical code],

    [`41`],
    [`RELJCT2_IM`],
    [Imputed version of the specific junction relationship (`RELJCT2`).],
    [Categorical code],

    [`42`],
    [`LGTCON_IM`],
    [Imputed version of the lighting condition (`LGT_COND`).],
    [Categorical code],

    [`43`],
    [`WEATHR_IM`],
    [Imputed version of the atmospheric/weather condition (`WEATHER`).],
    [Categorical code],

    [`44`],
    [`MAXSEV_IM`],
    [Imputed version of maximum injury severity (`MAX_SEV`).],
    [Categorical / ordinal],

    [`45`],
    [`NO_INJ_IM`],
    [Imputed version of the number of injured persons (`NUM_INJ`).],
    [Persons],

    [`46`],
    [`ALCHL_IM`],
    [Imputed version of alcohol involvement (`ALCOHOL`).],
    [Categorical code],

    [`47`],
    [`URBANICITY`],
    [Indicates whether the geographic area of the crash is classified by CRSS as urban or rural.],
    [Categorical: Urban/Rural],

    [`48`],
    [`REGION`],
    [U.S. geographic region in which the crash occurred: Northeast, Midwest, South, or West.],
    [Categorical code],

    [`49`],
    [`PSUSTRAT`],
    [PSU stratum used in the CRSS sampling design and statistical variance estimation.],
    [Sampling-design code],

    [`50`],
    [`PSU_VAR`],
    [PSU identifier specifically constructed for statistical variance estimation.],
    [Sampling-design code],

    [`51`],
    [`WEIGHT`],
    [Case sampling weight used to convert sampled CRSS crashes into nationally representative estimates.],
    [Numeric sampling weight],
  ),
) <attributes-table>

= Project Proposal

Traffic accidents are an important transportation safety concern, and understanding their spatial and temporal patterns, as well as the factors related to their occurrence and severity, can provide useful insights for transportation planning and safety analysis. In this project, we will use the US 2020 Traffic Accidents dataset obtained from Kaggle to investigate traffic accident patterns across the United States. We plan to perform exploratory data analysis and develop visualizations to examine the distribution of accidents by location, time of day, day of the week, and environmental and roadway conditions. We will also investigate how accident severity varies with factors such as weather, visibility, temperature, and road characteristics, using statistical analysis and visualizations to identify meaningful relationships and patterns in the data.

In addition to exploratory analysis, we plan to develop predictive models to investigate whether accident severity can be classified using the available accident characteristics. We will compare the performance of selected machine-learning models and examine the importance of different input variables in their predictions. The results will be interpreted in the context of transportation safety, with an emphasis on understanding patterns in the dataset rather than establishing causal relationships. Through this combination of visualization, statistical analysis, and predictive modeling, we aim to better understand traffic accident patterns and identify factors associated with accident severity, providing insights relevant to transportation engineering.

To add figures to your report, save the image file in the `figures` folder and use the `#figure` command as shown below to include it in your document. You can specify the width of the image and add a caption. Then you can reference the figure like this: @proofread.

#figure(
  image("figures/proof-read.png", width: 80%),
  caption: [A humble request. (Copyright: University of the Fraser Valley.)],
) <proofread>

=== First Subsubsection

You can make sub, sub-sub, and sub-sub-sub sections by adding `=` signs in front of the section title. There needs to be a space between the last `=` sign and the title text.

= Second Section

You can add tables using the `#table` command. Here is an example table:

#figure(
  caption: [Example Table],
  table(
    columns: (auto, auto, auto),
    table.header([*Column 1*], [*Column 2*], [*Column 3*]),
    "Row 1", "Data 1", [Data 2],
    image("figures/proof-read.png", width: 40%), "Data 3", "Data 4",
  ),
) <table-example>

You can reference the table like this: @table-example.

== Various Text Formatting Options

You can make text _italic_ by surrounding it with `_` symbols, *bold* by surrounding it with `*` symbols, and _*bold italic*_ by combining both. You can format `inline code snippets` by surrounding them with backtick (\`) characters.

You can create bullet point lists using `-` symbols:
- Bullet point 1
- Bullet point 2
  - Sub bullet point 1
  - Sub bullet point 2


You can create numbered lists using numbers followed by a period (or using `+` symbols, which number the items for you):
1. First item
2. Second item
  1. Sub item 1
  2. Sub item 2



== Equations

You can create equations using `$` symbols. For example, you can make an inline equation like this $E=m c^2$ or a displayed equation like this:

$ x < y => x gt.eq.not y $ <eq1>

You can reference the equation like this: Eq. @eq1.
