#import "@preview/charged-ieee:0.1.4": ieee

#show: ieee.with(
  title: [Exploring U.S. Traffic Accident Data, 2016–2020],
  authors: (
    (
      name: "Adityo Leonard",
      department: [Department of Civil and Environmental Engineering],
      organization: [University of Illinois Urbana-Champaign],
      location: [Urbana, IL, USA],
      email: "adityol2@illinois.edu",
    ),
    (
      name: "Akram Muhammad",
      department: [Department of Civil and Environmental Engineering],
      organization: [University of Illinois Urbana-Champaign],
      location: [Urbana, IL, USA],
      email: "akramm3@illinois.edu",
    ),
    (
      name: "Dumehlezi Jordan Mthombeni",
      department: [Department of Civil and Environmental Engineering],
      organization: [University of Illinois Urbana-Champaign],
      location: [Urbana, IL, USA],
      email: "dmtho@illinois.edu",
    ),
    (
      name: "Mohammadreza Rajaee",
      department: [Department of Civil and Environmental Engineering],
      organization: [University of Illinois Urbana-Champaign],
      location: [Urbana, IL, USA],
      email: "mrajaee2@illinois.edu",
    )
  ),
  index-terms: ("Optional", "Keywords", "Here"),
  bibliography: bibliography("refs.bib"),
)

= Data Description

The dataset used in this project is the US Traffic Accidents dataset available on Kaggle, which covers traffic crashes in the United States from 2016 to 2020. This dataset was generated by sampling records from the National Highway Traffic Safety Administration’s (NHTSA) Crash Report Sampling System (CRSS). CRSS itself is designed to provide a nationally representative sample of police-reported motor vehicle crashes in the United States. To develop CRSS, NHTSA uses a probability-based sampling process to select crash reports from law-enforcement agencies in selected geographic areas across the country. The selected police crash reports are then reviewed, interpreted, and coded by trained CRSS coders into standardized electronic data files.

The US Traffic Accidents dataset covers 259,077 crashes from 2016 through 2020 and is provided in CSV format. The records are organized into three main types of files: accident (acc), containing crash-level information; vehicle (veh), containing information about vehicles involved in each crash; and person (pers), containing information about drivers, passengers, pedestrians, and other persons involved. These files can be linked using the common CASENUM variable. Broadly, the dataset contains attributes describing the location and roadway characteristics of the crash, date and time, weather and environmental conditions, crash characteristics and contributing factors, vehicle information, and demographic or injury information for people involved in the crash.

Table 1 summarizes the main attributes that are expected to be relevant to this project; the complete CRSS dataset contains additional variables related to crash, vehicle, and person characteristics.



= Proposal (by Rajaee)

To add figures to your report, save the image file in the `figures` folder and use the `#figure` command as shown below to include it in your document. You can specify the width of the image and add a caption. Then you can reference the figure like this: @proofread.

#figure(
  image("figures/proof-read.png", width: 80%),
  caption: [A humble request. (Copyright: University of the Fraser Valley.)],
) <proofread>

=== First Subsubsection

You can make sub, sub-sub, and sub-sub-sub sections by adding `=` signs in front of the section title. There needs to be a space between the last `=` sign and the title text.

= Second Section

You can add tables using the `#table` command. Here is an example table:

#figure(
  caption: [Example Table],
  table(
    columns: (auto, auto, auto),
    table.header([*Column 1*], [*Column 2*], [*Column 3*]),
    "Row 1", "Data 1", [Data 2],
    image("figures/proof-read.png", width: 40%), "Data 3", "Data 4",
  ),
) <table-example>

You can reference the table like this: @table-example.

== Various Text Formatting Options

You can make text _italic_ by surrounding it with `_` symbols, *bold* by surrounding it with `*` symbols, and _*bold italic*_ by combining both. You can format `inline code snippets` by surrounding them with backtick (\`) characters.

You can create bullet point lists using `-` symbols:
- Bullet point 1
- Bullet point 2
  - Sub bullet point 1
  - Sub bullet point 2


You can create numbered lists using numbers followed by a period (or using `+` symbols, which number the items for you):
1. First item
2. Second item
  1. Sub item 1
  2. Sub item 2



== Equations

You can create equations using `$` symbols. For example, you can make an inline equation like this $E=m c^2$ or a displayed equation like this:

$ x < y => x gt.eq.not y $ <eq1>

You can reference the equation like this: Eq. @eq1.
